apiVersion: v1
kind: Service
metadata:
  name: "sample-service"
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetPort }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "sample-service.name" . }}
    environemnt: {{ .Values.environment }}
